config/routes.rb
Rails.application.routes.draw do

  root to: "posts#index"

  devise_for :users

  get "posts", to: "posts#index"
  get "posts/new", to: "posts#new"
  post "posts", to: "posts#create"
  delete "posts", to: "posts#delete"
  get "posts/:id", to: "posts#show", as: "posts_show"

  get "posts/:id/comments", to: "comments#show", as: "comments_show"
  post "posts/:id/comments", to: "comments#create", as: "comments_create"
  delete "posts/:id/comments", to: "comments#delete", as: "comments_delete"

  post "posts/:id/votes", to: "votes#create", as: "votes"
  get "posts/:id/votes", to: "votes#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates_presence_of :content, :user_id, :post_id
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user

	has_many :votes
	has_many :users, through: :votes

	has_many :comments, dependent: :destroy

	validates_presence_of :url, :title


	def vote_count
		self.votes.sum(:vote)
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
#  has_secure_password

  has_many :comments
  has_many :posts
  has_many :votes, through: :posts

  validates_presence_of :email, :username
  validates_uniqueness_of :email, :username

end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :post
	belongs_to :user

	validates_presence_of :user_id, :post_id
	validates_uniqueness_of :user_id, scope: :post_id

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # helper_method :current_user
  #
  # def current_user
  #   user_id = session[:user_id]
  #   user_id && User.find(user_id)
  # end
  #
  # def authenticate_user!
  #   unless current_user
  #     flash[:notice] = "You have to be logged in to do that."
  #     redirect_to login_path
  #   end
  # end

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :delete]

  def show
    @post = Post.includes(:user).find(params[:id])
    @comments = @post.comments.order(created_at: :desc).page(params[:page]).per(10)
    render :show
  end

  def create
    @post = Post.find(params[:id])
    @post.comments.create(user_id: current_user.id,
                         content: params[:content] )

    redirect_to comments_show_path(@post)
  end

  def delete
    @post =Post.find(params[:id])
    user = current_user
    comment = Comment.find(params[:comment_id])
    if comment && (user.id == comment.user.id)
      comment.destroy
      flash[:notice] = "Comment deleted successfully"
      redirect_to comments_show_path(@post)
    else
      flash[:notice] = "That comment doesn't belong to you!"
      redirect_to comments_show_path(@post), status: :unauthorized
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:index]

	def new
		@post = Post.new
		render :new
	end

	def create
		post = current_user.posts.new(title: params[:title],
																	url: params[:url])
		if post.save
			redirect_to posts_path(post)
		else
			flash[:errors] = post.errors.full_messages
			redirect_to posts_path(post)
		end
	end

	def index
		@posts = Post.includes(:user).order("created_at DESC").page(params[:page]).per(10)
    	render :index
	end

	def show
		@posts = current_user.posts.page(params[:page]).per(10)
		render :show
	end

  def delete
		@post = Post.find(params[:id])
		user = current_user
		if user.id == @post.user.id
			@post.destroy
			flash[:notice] = "Post deleted successfully"
			@posts = Post.page(params[:page]).per(10)
			redirect_to posts_path(@posts)
		else
			flash[:alert] = "That post doesn't belong to you!"
			redirect_to comments_show_path(@post)
		end
	end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
 ## TODO
  before_action :authenticate_user!, only: [:create]

  def create
    @post = Post.find(params[:id])
    vote = @post.votes.find_by(user_id: current_user.id)
    if(vote)
      vote.update(vote: params[:vote])
      redirect_to posts_path(@post)
    else
      @post.votes.new(user_id: current_user.id ,vote: params[:vote])
      if @post.save
        redirect_to posts_path(@post)
      else
        flash[:alert] = @post.errors.full_messages
        redirect_to posts_path(@post)
      end
    end
  end

  def index
    @post = Post.find(params[:id])
    @votes = @post.votes
    render :index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/show.html.erb
<div class="col-md-12">
  <h2>
    <a href="<%= @post.url %>"><%= @post.title %></a>
    <span class="post-url">(<%= @post.url%>)</span>
  </h2>
  <p>Submitted by <span class="comment-username"><%= @post.user.username %></span> <%= time_ago_in_words(@post.created_at) %> ago</p>
  <% if current_user && current_user.id == @post.user_id %>
      <p>
        <%= link_to "Nuke the post", posts_path(id: @post.id), method: :delete, class: "btn btn-xs btn-danger" %>
      </p>
  <% end %>
  <h4><%= pluralize(@post.comments.count, "comment") %></h4>
</div>

<div class="col-md-12">
<% if current_user %>
    <span class="comment-text">Commenting as: <span class="comment-username"><%= current_user.username %></span> </span>
    <%= form_tag comments_create_path(@post), method: :post do %>
        <div class="comment-field">
            <%= text_area_tag :content, nil, {cols: "50", rows: "7"} %>
        </div>

        <%= submit_tag "Let me be heard!", class: "btn btn-md btn-default"%>
    <% end %>
<% end %>
  </div>
  <div class="col-md-12"></div>
    <div class="col-md-4">
      <% @comments.each do |comment| %>
      <div class="panel panel-default">
        <div class="panel-heading">
         <em><span class="comment-username"><%= comment.user.username %></span> <%= time_ago_in_words(comment.created_at) %> ago</em>
         <% if current_user && current_user.id == comment.user.id %>
            <%= link_to "Delete", comments_delete_path(id: @post.id,comment_id: comment.id), method: :delete, class: "btn btn-xs btn-default" %>
          <% end %>
          <br/>
        </div>
        <div class="panel-body">
          <%= simple_format(comment.content) %>
        </div>
      </div>
      <% end %>
    </div>
  <div class="comments-nav">
    <%= paginate @comments %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Regreddit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
  <![endif]-->
</head>
<body>
<nav class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="<%= root_path %>">Regreddit</a>
          <%= link_to "Posts", posts_path, class: "navbar-brand" %>
        </div>
        <div class="nav navbar-collapse collapse">
          <div class="navbar-right navbar-brand">
            <% if current_user %>
              <%= link_to current_user.username, posts_show_path(current_user) %> <span class="badge"><%= current_user.posts.count %></span>
              <%= link_to "Logoff", destroy_user_session_path, method: :delete %>
            <% else %>
              Want to join? <%= link_to "Login", new_user_session_path %> or <%= link_to "Sign Up", new_user_registration_path %> in seconds.
            <% end %>
          </div>
        </div>
    </div>
</nav>

<div class="container">
  <div class="notice">
    <% if flash[:errors] %>
        <h4 class="alert alert-danger">
          <% flash[:errors].each do |error| %>
            <%= error %><br>
          <% end %>
        </h4>
    <% end %>
  </div>
  <div class="notice">
    <% if flash[:notice] %>
        <h4 class="alert alert-info"><%= flash[:notice] %></h4>
    <% end %>
    <% if flash[:alert] %>
        <h4 class="alert alert-warning"><%= flash[:alert] %></h4>
    <% end %>
  </div>

  <div class="container">
    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/posts/_posts.html.erb
<div class="col-md-10">

  <ul class="posts">
    <% @posts.each do |post| %>
        <li class="post">
          <div class="row">
          <div class="col-xs-10">
            <% if current_user %>
                <div class="arrows">
                  <%= link_to image_tag("arrow_up.png",class: "img-responsive img-arrow"), votes_path(post,vote: 1), method: :post %>
                  <br><span>(<%= post.vote_count %>)</span><br>
                  <%= link_to image_tag("arrow_down.png", class: "img-responsive img-arrow"), votes_path(post,vote: -1), method: :post %>
                </div>
            <% end %>
            <div class="test-post">
              <%= link_to post.title, post.url, class: "post-link" %> <span class="post-url">(<%= post.url %>)</span>
            </div>
            <div class="comment-link">
              <em>Submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.username %></em>
              <br><%= link_to pluralize(post.comments.count, "comment"), comments_show_path(post), class: "badge" %>
            </div>
            </div>
            </div>
        </li>
    <% end %>
  </ul>
</div>
<div class="col-md-2 posts-nav">
  <%= paginate @posts %>
  <%= link_to "Add a Post", posts_new_path, class: "btn btn-primary btn-lg" %>
</div>

app/views/posts/index.html.erb
<div class="page-header">
  <h2>All Posts</h2>
</div>
  <div class="col-md-10">

	<ul class="posts">
    <% @posts.each do |post| %>
        <li class="post">
            <%= link_to post.title, post.url, class: "post-link" %> <span class="post-url">(<%= post.url %>)</span>
            <div class="comment-link">
                <em>Submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.username %></em>
                <br><%= link_to pluralize(post.comments.count, "comment"), comments_show_path(post), class: "badge" %>
            </div>
        </li>
    <% end %>
    </ul>
  </div>
    <div class="col-md-2 posts-nav">
    	<%= paginate @posts %>
        <%= link_to "Add a Post", posts_new_path, class: "btn btn-primary btn-lg" %>
    </div>

app/views/posts/new.html.erb
<%= form_tag(posts_path) do %>
    <h1>Create new post</h1>
	 <div class="panel panel-default">
     <div class="panel-heading">
        <%= label_tag "Title" %>
    </div>
    <div class="panel-body">
      <%= text_field_tag :title, nil, placeholder: "Enter your post title here.", class: "form-control" %>
    </div>
   </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <%= label_tag "URL" %>
      </div>
      <div class="panel-body">
        <%= text_field_tag :url, nil, placeholder: "Enter your URL here.", class: "form-control" %>
      </div>
      </div>
    <div class="container">
      <%= submit_tag "Post", class: "btn btn-default btn-lg" %>
<% end %>
    <%= link_to "Nevermind", posts_path, class: "btn btn-primary btn-lg" %>
  </div>

app/views/posts/show.html.erb
<div class="page-header">
  <h2><%= current_user.username %>'s Posts</h2>
</div>

<%= render partial: "posts" %>